language: php

php:
  - 7.3
  - 7.4
  - 8.0

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-source

script:
  - phpunit 
