language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit 
  - ./wp-vulnerability-check --path ./tests/data/vPlugins/ --token c0DR3SJklWNn26oP6lZ7ybrHCrR4UaSqD0dhKcC2m0U --output READABLE 
