language: php

php:
  - 5.6
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-source

script:
  - phpunit 
