# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: composer install --no-interaction --prefer-source
  test-5.6:
    docker:
        - image: umutphp/php-docker-images-for-ci:7.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: composer install --no-interaction --prefer-source
      - run: ./vendor/bin/phpunit
  test-7.0:
    docker:
        - image: umutphp/php-docker-images-for-ci:7.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: composer install --no-interaction --prefer-source
      - run: ./vendor/bin/phpunit
  test-7.1:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: composer install --no-interaction --prefer-source
      - run: ./vendor/bin/phpunit
  test-7.2:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: composer install --no-interaction --prefer-source
      - run: ./vendor/bin/phpunit
  test-7.3:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.3
    working_directory: ~/repo
    steps:
      - checkout
      - run: composer install --no-interaction --prefer-source
      - run: ./vendor/bin/phpunit
workflows:
  version: 2
  build_and_create:
    jobs:
      - build
      - test-5.6:
          requires:
            - build
      - test-7.0:
          requires:
            - build
      - test-7.1:
          requires:
            - build
      - test-7.2:
          requires:
            - build
      - test-7.3:
          requires:
            - build
