name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: composer-normalize-action
      uses: localheinz/composer-normalize-action@0.4.2
    - name: PHP Lint
      uses: michaelw90/PHP-Lint@1.0.0
