name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://umutphp/php-docker-images-for-ci:7.1
      - name: composer-normalize-action
        run: composer normalize --dry-run
      - name: PHP Lint
        run: parallel-lint --exclude vendor .
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://umutphp/php-docker-images-for-ci:7.1
      - name: PHPCodeSniffer
        run: var-dump-check .
