name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu:latest
    container:
      image: umutphp/php-docker-images-for-ci:7.2
    steps:
      - name: Composer Normalize Action
        run: composer normalize --dry-run
      - name: PHP Lint
        run: parallel-lint --exclude vendor .
  check:
    runs-on: ubuntu:latest
    container:
      image: umutphp/php-docker-images-for-ci:7.2
    steps:
      - name: VarDump Checker
        run: var-dump-check .
