name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: composer-normalize-action
        uses: docker://umutphp/php-docker-images-for-ci:7.1
        run: composer normalize --dry-run
      - name: PHP Lint
        uses: docker://umutphp/php-docker-images-for-ci:7.1
        run: parallel-lint --exclude vendor .
  check:
    runs-on: ubuntu-latest
    steps:
      - name: PHPCodeSniffer
        uses: docker://umutphp/php-docker-images-for-ci:7.1
        run: var-dump-check .
